---
authors:
  - Taylor Kimball (https://github.com/tkimball83)
  - Nayeem Syed (https://github.com/wizardsupreme)
build_ignore:
  - .gitignore
description: A collection of linux roles
dependencies:
  ansible.posix: 2.0.0
  community.docker: 4.3.1
  community.general: 10.3.1
documentation: https://github.com/yamlspace/ansible-collection-linux/blob/main/README.md
homepage: https://www.yaml.space
issues: https://github.com/yamlspace/ansible-collection-linux/issues
license:
  - GPL-3.0-or-later
name: linux
namespace: yamlspace
readme: README.md
repository: https://github.com/yamlspace/ansible-collection-linux
tags:
  - cloud
  - infrastructure
  - linux
version: 1.7.3
...
