---
- name: Converge
  hosts: all
  roles:
    - role: linuxhq.linux.monit
      monit_alert:
        - name: monit@linuxhq.net
          rules:
            - not on { instance, action }
      monit_daemon: 60
      monit_eventqueue_basedir: /var/tmp
      monit_eventqueue_slots: 2048
      monit_exec:
        - name: dev_null.sh
          base64: |
            IyEvYmluL2Jhc2gKCmVjaG8gMSA+IC9kZXYvbnVsbAo=
      monit_filesystem:
        - name: root_linuxhq
          rules:
            - path /
            - if space usage gt 80%
            - for 5 cycles then alert
      monit_host:
        - name: https
          rules:
            - address 127.0.0.1
            - if failed port 443
            - for 5 cycles then alert
      monit_program:
        - name: httpd
          rules:
            - path /usr/bin/systemctl --quiet is-active httpd.service
            - if status ne 0
            - for 5 cycles then alert
      monit_start_delay: 120
...
