---
- name: Converge
  hosts: all
  roles:
    - role: linuxhq.linux.kopia
      kopia_maintenance:
        - --enable-quick true
      kopia_policies:
        - target: /home/linuxhq/containers
          flags:
            - --compression gzip
            - --keep-annual 0
            - --keep-hourly 24
            - --keep-latest 2
            - --keep-monthly 3
            - --keep-weekly 4
            - --snapshot-interval 1h
      kopia_repository:
        location: s3
        flags:
          - "--access-key {{ aws_access_key_id }}"
          - "--bucket kopia-backups"
          - "--endpoint s3.us-west-1.amazonaws.com"
          - "--prefix {{ inventory_hostname }}/"
          - "--region us-west-1"
          - "--secret-access-key {{ aws_secret_access_key }}"
      kopia_server: true
...
